### ISSUE TITLE
[QUESTION] Planning to consume Release 1.4.0 of WebRTC C SDK in our production.

### ISSUE THREAD

**Issue by HimanshuVerma18111989** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1006]
Hi Team,

I can see the last release was at 10th November 2020. I am planning to consume this release in our production. Just wanted to get your thoughts on this, do you guys recommend to consume the release 1.4.0 or should i consume the latest commit? Are there any releases planned for this month?

**Comment by MushMal** [comment]
We have some info on how we version our releases here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#versioning

Our strategy is to have the master branch always "good to go" and our tests should pass in order to push any PR into master branch. However, for a particular release we run extra tests and canaries to ensure stability in some edge cases. 

Depending on your timeline, you might wait some to get a new 1.5.0 release which will be cut on top of the latest which would include everything from 1.4.0 and some other bug fixes. The release notes will contain more info. 

No ETA yet as of when we will cut the release

**Comment by disa6302** [comment]
Closing based on tag
