### ISSUE TITLE
[QUESTION] Viewer cannot reconnect to Master when network changes

### ISSUE THREAD

**Issue by meilin-shi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1106]
I facing this issue that sample Viewer cannot reconnect  to Master when network changed. How should I do to reconnect viewer and master?  Thank you.

**Comment by disa6302** [comment]
What do you mean by network changing? Do you mean switching network interface type, say from WiFi to LTE? 

If it is the case, ICE renegotiation needs to take place. This can be done using the [iceRestart](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cb5b34baa2c808ae664bdb36e01968465d884e64/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1589) API. 

Note that iceRestart must be initiated by the viewer because an offer with `iceRestart` option needs to sent before invoking this API.

You can understand more about ICE restart [here](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart).

**Comment by meilin-shi** [comment]
> What do you mean by network changing? Do you mean switching network interface type, say from WiFi to LTE?
> 
> If it is the case, ICE renegotiation needs to take place. This can be done using the [iceRestart](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cb5b34baa2c808ae664bdb36e01968465d884e64/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1589) API.
> 
> Note that iceRestart must be initiated by the viewer because an offer with `iceRestart` option needs to sent before invoking this API.
> 
> You can understand more about ICE restart [here](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart).

Thank you for your reply. I think I get how to use iceRestart by your answar. But I cannot get the time when state changed, I use [signalingClientGetCurrentState()](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cb5b34baa2c808ae664bdb36e01968465d884e64/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1892), [peerConnectionOnConnectionStateChange()](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cb5b34baa2c808ae664bdb36e01968465d884e64/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1459)  and gatherIceServerStats() and some other function in the block function [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cb5b34baa2c808ae664bdb36e01968465d884e64/samples/kvsWebRTCClientViewer.c#L163) to get the state, but it seems that the connect state is not changed when I changed connecting network from wifi A to wifi B,  could you tell me how to get the new state

**Comment by disa6302** [comment]
@meilin-shi , 

You could use [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cb5b34baa2c808ae664bdb36e01968465d884e64/samples/Common.c#L50) section to invoke the restart API. When data exchange fails due to network, this specific enum will be set. And you can act upon it. 

Do you data exchange failing when your network switches? I would suggest you to test the code you add by switching the network off in the middle of the session and seeing how the SDK reacts. If it works that way, network switching should work wrt the SDK as well.

**Comment by meilin-shi** [comment]
Thank you for your reply.
I use _peerConnectionOnConnectionStateChange(pSampleStreamingSession->pPeerConnection, (UINT64) pSampleStreamingSession, onConnectionStateChange)_, the configuration _onConnectionStateChange_ is the function you suggest me to use to get the state, and I test the code, log file is [kvsFileLog.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/6187174/kvsFileLog.txt).
As you can see in the file, I can get frames from Master at the beginning, Master is running at my phone, the Viewer is running at my computer, if I switch the network of my computer, I can only send data but cannot receive data, the _pKvsPeerConnection->connectionState_ I print is still 3(meaning is _RTC_PEER_CONNECTION_STATE_CONNECTED_).
I think function _peerConnectionOnConnectionStateChange()_ will call the callback function _ onConnectionStateChange()_ if the connection state changed, I print the _pKvsPeerConnection->connectionState_  in function _peerConnectionOnConnectionStateChange()_ . Am I did right ? Perhaps I passed the wrong configuration to the function or I should use the function _ onConnectionStateChange()_ individually?

**Comment by disa6302** [comment]
@meilin-shi , 

`peerConnectionOnConnectionStateChange` sets the callback, does not invoke it. As the name suggests, callbacks are invoked automatically in case of an event. Please follow what I mentioned in my previous comment to add your functions call in the line I pointed to and see how it reacts. In fact, I would suggest you to not make any code modifications except adding a logging [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/cb5b34baa2c808ae664bdb36e01968465d884e64/samples/Common.c#L50) and see if the state transition occurs when you change from WiFi to LTE or turn off the network.

**Comment by meilin-shi** [comment]
I add a logging at the section and not modify any other code , unfortunately the logging is not print when I change the network. 
It seems the state transition not occurs when I switch or turn off the network.

**Comment by meilin-shi** [comment]
I add a logging at the section and not modify any other code , unfortunately the logging is not print when I change the network. 
It seems the state transition not occurs when I switch or turn off the network.

**Comment by disa6302** [comment]
@meilin-shi , 

Not sure what is going on. I tried disconnecting the network and I do enter the FAIL state. It is possible the detection is taking some time.

**Comment by meilin-shi** [comment]
OK, Thank you. Closing this issue
