### ISSUE TITLE
[QUESTION] Why calling signalingClientSendMessageSync() returns 0xf error status

### ISSUE THREAD

**Issue by zwei333** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1145]
We have seen this problem once and captured the log (It might have happened many times):
We called signalingClientSendMessageSync() to send an "Answer" to peer.
15 seconds later, signalingClientSendMessageSync()  returns with error status 0xf.
2021-04-16 17:49:34 ERROR   signalingSendMessageSync(): operation returned status code: 0x0000000f
However, subsequent calls of signalingSendMessageSync() for sending ICE candidates all succeeded. 
We wonder what is meaning of status code: 0x0000000f?  Is this a critical error?
SDK version 1.5.0

**Comment by MushMal** [comment]
All status codes are defined in the public headers. In particular to KVS WebRTC, the status codes starting from 0x55000000 are defined in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h

Status codes from 0x15000000 are defined in https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/include/com/amazonaws/kinesis/video/common/Include.h and the status codes starting from 0x00000000 are defined in https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h


The one that you are referring to is defined here: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h#L478

which is STATUS_OPERATION_TIMED_OUT


Now, the other question is why is it timing out. Normally, the signaling backend would return OK even in case of the peer not being available as it's more of a relay of the messages. In this case, it seems that there must have been an issue with the networking itself. In order to debug it further, you might want to enable the verbose logs and compile it with the debug version of libWebSockets.

**Comment by zwei333** [comment]
Thanks.  Looks like a transient network connectivity issue.  Messages before and after this all made through.  Maybe we should retry once in case of this

**Comment by disa6302** [comment]
Closing based on comment. Feel free to reopen if you have any more questions.
