### ISSUE TITLE
STACK SIZE required?

### ISSUE THREAD

**Issue by mukesh-2538** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1181]
**Observation:**
*HandleOffer() requires a stack size of 27KB. Current stack value set on my dev board is 8KB*

**Question:**
*1. what should be the maximum stack size required by the KVS library?*

**Comment by MushMal** [comment]
Stack size can be scenario dependent. KVS has been tested with 500KB stack size (windows machine)

**Comment by Venkee1** [comment]
@MushMal  Is this per thread that KVS library creates or total stack size used by the process?

**Comment by MushMal** [comment]
On a commodity OS-es with each thread getting allocated 500KB of virtual memory. @ycyang1229 do you have more info on running on a tighter stack platforms?

**Comment by ycyang1229** [comment]
I did not do a detailed measurement of the stack size for this sdk without any modification, but I did remember that HandleOffer needs 2xKB. In my case, I remember I reduced it to 10KB or less. 

In my case, my codebase creates the following threads. So if stack size is yours consideration, you need to take care of them. 
--
sampleTimer => sample code
video source => sample code
signaling timer => webrtc 
lwsListener => webrtc
lwsDispatch => I merged the processes of handling lws messages into one static process. If your system can hold dynamic detached threads, you do not need to do this. But you need to know the number of threads may be 1x or even more, it depends on the number of the viewer's candidates and how fast your master runs.
peerTimer => webrtc
connListener => webrtc

The number of threads for usrsctp depends on what feature you use and what kind of sockets does your tcp/ip stack supports. In my case, there are only three threads. But if you are on ubuntu, you may have more.
sctp iterater => usrsctp. 
sctp udp ipv4 => usrsctp
sctp timer => usrsctp

Do you want to reduce the stack size or know how much size you need to set?
If you want to reduce your stack size, you need to change the buffer allocation from stack to heap. 
If you want to control the size of stack, you need one interface to control the thread size. Since those threads need different stack size.
If you just want to set one maximum stack size for all the threads, 2xKB should be fine.

**Comment by disa6302** [comment]
Assuming answered, closing this.
