### ISSUE TITLE
[QUESTION] Under what circumstances will the mediaThreadStarted variable in PSampleConfiguration become FALSE

### ISSUE THREAD

**Issue by zz-svg** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1219]
We found in the test that the video sending thread is a resident thread, will it be a resident thread?
When there is an APP connection, the device side will check the mediaThreadStarted flag. If it is FLASE, it will create a video sending thread and set mediaThreadStarted to TRUE. When the APP exits, it does not change mediaThreadStarted to FALSE. My question is under what circumstances will it be changed to FALSE, and the result of the test now is always TRUE. This result will cause the video sending thread to always exist, which will cause the occupation of system resources.
![image](https://user-images.githubusercontent.com/65853976/128468707-659d8303-ba41-4bf9-92bc-0c897a4a34a0.png)

**Comment by disa6302** [comment]
The flag is cleaned up here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/07deb1795e01fbd97bdb8d9c556cb4ab3bc60ea0/samples/Common.c#L177

However, what is missing is canceling the `mediaSenderRoutine` after `CleanUp` because just setting `mediaThreadStarted` to `FALSE` is not helping anything. Will investigate a little more and update this thread.

**Comment by disa6302** [comment]
Issue fixed here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1227
Closing.
