### ISSUE TITLE
[QUESTION] Choppy Audio and Jitter Buffer Latency

### ISSUE THREAD

**Issue by wlinInspire** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1222]
We experience choppy audio when master and viewer are not in the same LAN. Changing `DEFAULT_JITTER_BUFFER_MAX_LATENCY` from the default 2 seconds to 10 seconds helps a lot. But after connecting for a while under 10 seconds max latency, the audio becomes choppy again. We see some frame drops shown below. Is there any other way to solve frame drop issue besides increasing `DEFAULT_JITTER_BUFFER_MAX_LATENCY` ?

```
2021-08-09 19:03:19 WARN    onFrameDroppedFunc(): Frame with timestamp 2332017859 is dropped!
2021-08-09 19:03:19 WARN    onFrameDroppedFunc(): Frame with timestamp 2332041859 is dropped!
2021-08-09 19:03:28 WARN    onFrameDroppedFunc(): Frame with timestamp 2332443139 is dropped!
```

**Comment by jdelapla** [comment]
Hello @wlinInspire ,

Some questions:

1. Do you know what your upload rate on this device is? Can you run an iperf test?
2. What is your bitrate set to on this camera?

I'm asking these questions because the information you've given has led me to believe that your camera simply cannot upload the frames/audio at the quality you have set as fast as it is generating them. The jitter buffer only drops frames whenever it has noticed that the oldest frame in the buffer is MAX_LATENCY seconds older than the newest frame/packet put in the buffer.

The best solution would be to adapt your audio/video quality to match your available upload speed.

**Comment by wlinInspire** [comment]
@jdelapla 
1. The device is the master sending out video (H264, 15fps, 640x480) and audio (Opus 48kHz). The viewer is the chrome browser. The choppy audio comes out of the speaker of the device.
2. I don't know the bitrate. I simply use the gstreamer pipeline in the sample code `appsrc name=appsrc-audio ! opusparse ! decodebin ! autoaudiosink` to play the audio received

Since the choppy audio is coming out of the camera's speaker, I believe it is not about uploading but downloading. Let me know there is any test we can do

**Comment by wlinInspire** [comment]
@jdelapla how do I lower the bit rate from browser side? We are using aws webrtc JavaScript in the browser?
