### ISSUE TITLE
[FEATURE] Add  RTCSignalingState and peerConnectionOnSignalingStateChange

### ISSUE THREAD

**Issue by kev-the-dev** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1278]
**Is your feature request related to a problem? Please describe.**
Users have no access to the current signaling state of a peer connection, except for possibly tracking this state using a wrapper external to the library.

**Describe the solution you'd like**

Implement the following components of the w3c webrtc spec:

* [RTCSignalingState](https://www.w3.org/TR/webrtc/#rtcsignalingstate-enum)
* [signalstatechange event](https://www.w3.org/TR/webrtc/#event-signalingstatechange)

Implement this as follows:

Add enum RTC_SIGNALING_STATE similar to [RTC_PEER_CONNECTION_STATE](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-c/group__PublicEnums.html#ga1a8485527953d22957465fb016c44bec).

Add peerConnectionOnSignalingStateChange callback registration function, simlar to [peerConnectionOnConnectionStateChange](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-c/group__PublicMemberFunctions.html#gae937526652e3287c3e2dd9bee74ea799)

Add logic to other peerConnection functions to appropriately set this state and trigger the callback when it changes

**AFAIK, this library does not support panswer/poffer (partial anwers/offers), so these states will be excluded / unreachable**

**Describe alternatives you've considered**
Implementing a wrapper in my application to track this state. While function, this would be more useful as contributed code for other users of this library.

**Additional context**
In my application, I want to implement a "auto-retry" mechanism which will do signaling in a loop when the connection fails. Having access to the current signaling state allows this logic.

**Comment by disa6302** [comment]
We do track signaling state changes in this callback: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/d08634bda8b32b0e9993a83835c4f0481c060abd/samples/Common.c#L75

The structure can be found here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/d08634bda8b32b0e9993a83835c4f0481c060abd/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1325

Our signaling state is not the same as `RTCSignalingState`. `RTCSignalingState` is the context before our signaling state machine.

The implementation of this would most likely tie with this: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/d08634bda8b32b0e9993a83835c4f0481c060abd/samples/Common.c#L1233. At this point, users can implement a similar logic in the samples itself. I am still going to let this enhancement ticket be open because adding it in our SDK would simplify this for customers.

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
