### ISSUE TITLE
[QUESTION]Memory reduction when not using Media Stream

### ISSUE THREAD

**Issue by pipsnh02** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1316]
Our system doesn't use Media Stream, so
We would like to reduce the memory usage related to RTCRtpTransceiver.

After investigating the SDK, I found that JitterBuffer uses 140KByte.
Therefore, I would like to change the size of JitterBuffer as follows.

JitterBuffer.h
#Define JITTER_BUFFER_HASH_TABLE_BUCKET_COUNT 3000
↓
#Define JITTER_BUFFER_HASH_TABLE_BUCKET_COUNT (MIN_HASH_BUCKET_COUNT)

Here are some things to check about the above.
① Is there any problem with the above change method?
(2) Is there any point other than the above that can reduce the memory usage?
　*The data channel is used and cannot be removed.

**Comment by hassanctech** [comment]
Just want to make sure I understood correctly so no media stream means you're only using the data channel, is that right?

**Comment by pipsnh02** [comment]
hassanctech Thank you.

Yes, that's right.
Use only the data channel without using the media stream.

**Comment by MushMal** [comment]
Minimizing the runtime footprint is an iterative process and it's heavily related to your custom scenario. If you only need the data channel without any other WebRTC features then perhaps WebRTC might not be the right solution for you overall. Why not using some other communication means? However, if you are using signaling client for the discovery and DTLS for the transport protection then you might consider changing the pre-defined defaults to minimize the memory impact. The largest memory/buffer usage within the WebRTC context would be the jitter buffer in that case.

**Comment by pipsnh02** [comment]
MushMal　Thank you.

By changing the size of JitterBuffer, we were able to confirm the reduction in the amount of allocation.
However, we need to reduce our memory usage even more. Is there any other place where memory can be reduced?

**Comment by MushMal** [comment]
You might be able to shed a few KBs by changing the message buffer size in the signaling client but otherwise, it's a very lightweight. You might want to look at the open source dependencies and see if you can configure those to run with smaller footprint but I don't have any guidance for those off the top of my head (for example, using mbedTLS vs OpenSSL might prove to have a smaller footprint).

**Comment by disa6302** [comment]
@pipsnh02 ,

There isnt any other way to reduce memory consumption. As @MushMal mentioned, using mbedTLS would help a little, but otherwise, our SDK is quite lightweight. I am closing this issue out given we have provided available alternatives. Feel free to reopen if you have any more questions. Thank you!
