### ISSUE TITLE
KVS WebRTC Test Page as viewer(disable stun/turn, close ice trickle) can't connect to kvs-webrtc-sdk-c as master which deployed on ec2.

### ISSUE THREAD

**Issue by HiconKong** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1330]
viewer: echo show or KVS WebRTC Test Page

master:kvs-webrtc-sdk-c(Version:clone from master branch on 2021/06/29) on ec2

question: 
i would like to make echoshow as viewer which can connect with  kvs-webrtc-sdk-c as master . and deployed c-sdk on ec2. At first we use KVS WebRTC Test Page as viewer it perform excellent. But when i disable stun/turn and close ice trickle or use echo show as viewer, it become worst that ice agent state always fail.

if you need logs and stun packet data, pls remain your email.  tks.

**Comment by hassanctech** [comment]
You *must* disable trickle ice if you're using Echo Show as viewer because Alexa doesn't support trickle ice.  

If you can provide logs here as an attachment that would be better, otherwise you can send it here:  kinesis-video-support@amazon.com.  VERBOSE level logs would be best if you can get them, from both master and viewer side (as much as you can provide).

Final comment I would recommend you always use the latest official release, which is:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/releases/tag/v1.6.0 -- from Aug 3.

**Comment by disa6302** [comment]
No response. Closing.
