### ISSUE TITLE
[QUESTION] Use public IP for producer and skip ICE?

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1367]
When I have a publicly accessible IP of a producer, how can I skip the whole ICE procedure as a client will always be able to setup a peer connection?

I've seen the `iceSetInterfaceFilterFunc` callback on the `RtcConfiguration` but that will still do the ICE flow.

**Comment by disa6302** [comment]
ICE cannot be skipped. The role of ICE is to ensure the right candidates are chosen to establish communication. `iceSetInterfaceFilterFunc` is used to filter network interfaces that need to be used. Some applications might want to use it in order to reduce the candidate gathering time. If you know which interface has the IP address that is publicly accessible,  you can this function to gather candidates only from that interface which will speeden up the connection setting time.

Here is an example callback: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/22c9e3d7932365f0d04181b339f17e4870036f5c/samples/Common.c#L282

Resolving assuming question answered. Feel free to reopen if you have more questions.

**Comment by roxlu** [comment]
Thanks @disa6302, I was indeed thinking to use that.
