### ISSUE TITLE
[BUG] Monotonic time should be used for calculating the durations such as timeouts

### ISSUE THREAD

**Issue by tuncalie** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1420]
**Describe the bug**
For calculation of timeouts, `GETTIME` function is used. 
`GETTIME` is defined as `globalGetTime` function. 
As it can be seen in  https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/Time.c#L45 this function reads the time using `CLOCK_REALTIME` as the clock id when calling `clock_gettime`. This is the wall clock and it can go forward and back with NTP synchronizations. Using this time for calculating the time passed will result in unexpected behavior.

Instead, time should be read using `CLOCK_MONOTONIC` as the clock id when calling `clock_gettime` for the time information that will be used to measure the time passed. 

Please refer to [clock_gettime man page](https://linux.die.net/man/3/clock_gettime) for more details.
This discussion can also be used as a reference: https://stackoverflow.com/questions/3523442/difference-between-clock-realtime-and-clock-monotonic

**SDK version number**
1.7.1 (and all previous)

**Expected behavior**
Timeouts should be calculated accurately.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by MushMal** [comment]
Historically, it was a single clock definition - GETTIME which could be mapped to anything (or overridden like in case of testing or other runtimes). Later, a new time function was added - GETREALTIME https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/Time.c#L4 which is used to measure durations with precision. It was supposed to be mapped to the monotonic function but the latest code shows it points to the same realtime. This one is used in the CVAR wait functionality for example. I believe the default time implementation needs to be revisited again. The main points to take though is that the time functionality can be overridden easily by setting globalGetTime function pointer like it's originally done in the codebase:

https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/9ef93e5a41465ec0c847b8e1ee30ac9ba29fdb7f/src/utils/src/Time.c#L3


The other thing to remember is that other runtimes would enforce usage of a particular implementation - for example Java through JNI. And the third point is that the time should be agreed with the auth token retrieved from the backend in order to communicate.

**Comment by tuncalie** [comment]
Yes, I believe the time used for some functionality like communicating with backend should still be the wall time but the time used in calculating timeouts (for instance https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/TurnConnection.c#L215) should be the monotonic clock.

Should we expect an update in the SDK soon to address this?

**Comment by disa6302** [comment]
@tuncalie , 

I agree we should be using MONOTONIC. As far as an update on when this will be done, I will update the ticket after internal discussion.

**Comment by tuncalie** [comment]
Before the bot closes this issue, yes this is still happening.
