### ISSUE TITLE
[BUG] Cannot show stream video in KVS WebRTC Test Page

### ISSUE THREAD

**Issue by alexandrecolombobr** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1430]
**Logging**
Screenshot of the "KVS WebRTC Test Page" (https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html) log area below:
![error-sample](https://user-images.githubusercontent.com/11586198/158444948-c8e7d82a-82cd-4d1f-97e7-eb871a86eb6a.png)

**Describe the bug**
We are trying to view the video stream sent by an embedded device that acts as a producer:
![arch](https://user-images.githubusercontent.com/11586198/158444891-886f921e-798d-447e-9723-ab735cc65df9.png)
When using the viewer present in the AWS control panel, the video stream is displayed correctly (https://us-east-1.console.aws.amazon.com/kinesisvideo/home?region=us-east-1#/signalingChannels/signalingChannelName/20072021).

However, when we try to use the "KVS WebRTC Test Page" example, it cannot consume the video stream, and apparently it is always trying to use the computer's webcam to act as a producer.

**SDK version number**
Commit: f3a34c2

**To Reproduce**
1. Start the kvsWebrtcClientMasterGstSample application in embedded with the channel-name, video-only and testsrc arguments
2. Start the "KVS WebRTC Test Page" viewer with the assigned channel settings (Region, Access Key ID, Secret Access Key, Channel Name, STUN/TURN checked and Use trickle ICE checked)
3. Wait for video stream to appear.

**Expected behavior**
"KVS WebRTC Test Page" example panel should connect to the signaling channel and show the video stream.

**Embedded device**
- ARM Linux 5.4.97 device with 1GB RAM and Freescale i.MX6 Dual Lite CPU

**Comment by hassanctech** [comment]
You are on a release from over 1 year ago, please use the latest release v1.7.2.

Also, the KVS WebRTC test page does use the webcam that is the expected behavior.  But if you run the gst sample the test page should show both the webcam video AND the test video from the `kvsWebrtcClientMasterGstSample` sample application.  If you do not want to use the webcam stream then de-select the video option in the UI.  It looks like you have not granted the correct permissions in your browser that is why it is failling.
