### ISSUE TITLE
[FEATURE] Improve writeFrame() Performance

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1457]
**Is your feature request related to a problem? Please describe.**
We use armv7 CPU on our devices. We also stream h264 stream with video stream only. When the bitrate hits 2Mbps, writeFrame() starts to take a bit longer to process and peaks at about ~200ms to ~500ms at times when sending keyframes. We would love to see if there is room for optimization for this function.

**Describe the solution you'd like**
Optimization of writeFrame function.

**Describe alternatives you've considered**
We temporarily improved the media thread priority and this improved a bit.

**Comment by jdelapla** [comment]
The description is unclear if the latency is from internal mechanisms of the function or latency due to a specific network environment. Writeframe() is a blocking function that packetizes and sends media over a socket, if there is an optimization found that is specific to the SDK and not a given network environment we would greatly appreciate a detailed accounting of said optimization or a PR.
