### ISSUE TITLE
Do I need to change the sample program when using wwan0?

### ISSUE THREAD

**Issue by hiroshifractal** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1516]
Other aws services are connecting without any problems.
Do I need to change the sample program when using wwan0?

_Originally posted by @hiroshifractal in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1488#issuecomment-1155904571_

**Comment by hassanctech** [comment]
I'm following the several issue you created it looks like the issue was never resolved.  I see that your describe call succeeds with the get endpoint call.  When you hit this program do you always see that describe succeed and get endpoint fail or is it random?

Also I see these lines indicating the issue:

```
[2022/06/04 11:37:22:9381] N: lws_sort_dns: 54.65.31.48 has no route out
```

There is a PR that @jdelapla created https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1469 but it was never merged (looks like it is failing a format check) but it seems to be in response to the same issue.  

Could you please try something in this section:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/CMake/Dependencies/libwebsockets-CMakeLists.txt#L33

Can you please add `-DLWS_WITH_NETLINK=0` and try? You can try it on top of the latest release 1.7.3.

**Comment by hiroshifractal** [comment]
I always get the same error.
Thank you. I will add the commandand try it.

**Comment by hassanctech** [comment]
@hiroshifractal any updates?

**Comment by hiroshifractal** [comment]
I added -DLWS_WITH_NETLINK=0 and try, but the same log was output.
[log_220726.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/9186791/log_220726.txt)

**Comment by disa6302** [comment]
@hiroshifractal , 

To ensure it did not work, did you clean build and try?

**Comment by hiroshifractal** [comment]
I ran "cmake .." and "make", before running the kvsWebrtcClientMasterGstSample. 
What else do you need to do?

**Comment by hiroshifractal** [comment]
Thank you for your help.
I'll try after August 13th because I don't have the device.

**Comment by hiroshifractal** [comment]
Thank you for your help!
Tried as per your help and solved.
I appreciate you sincerely.

As for the other issue, will it work on safari?
This has been an issue for some time.

**Comment by disa6302** [comment]
@hiroshifractal , 

Please direct your issue to the appropriate repository. If you are using the JS SDK, you can open your issue on that. Thank you. Resolving this now.
