### ISSUE TITLE
[QUESTION] How to Stop Master when viewer click on stop viewer ?

### ISSUE THREAD

**Issue by Ramnirmal0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1559]
Master camera and streaming can be started when viewer click **start viewer** . so similiarly how master streaming can be closed when viewer click **stop viewer**  ? 

observation:
i can see my master webcam only turn on  ans stream when i click on start viewer. so when i click on stop viewer master is still ON / camera is not turning Off

how to stop master on click of stop viewer or any other button like "End session" or something . assume there will be only one viewer for each master.

**Comment by niyatim23** [comment]
Hi @Ramnirmal0, I think you meant to ask this question in the WebRTC JS SDK. So far, we do not have something to end the session since the sample's master is meant to cater to multiple viewers. However, you can try using [this](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceconnectionstatechange_event) event to shut down the master when the user drops.

Closing assuming answered. Feel free to reach out to us with further issues / questions
