### ISSUE TITLE
Duplicate definitions in RtcpPacket.h

### ISSUE THREAD

**Issue by KittyLiou** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1648]
I wonder why there are several duplicate definitions in [src/source/Rtcp/RtcpPacket.h](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Rtcp/RtcpPacket.h).
For example: 
`RTCP_PACKET_SENDER_REPORT_MINLEN`, `RTCP_PACKET_RECEIVER_REPORT_BLOCK_LEN`, `RTCP_PACKET_RECEIVER_REPORT_MINLEN`

**Comment by sirknightj** [comment]
Hi @KittyLiou,

Thanks for the question and keen observation!

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/b820e2ea3d28c670da2fbc789face742cb949ef1/src/source/Rtcp/RtcpPacket.h#L29-L47

The above looks to be an error, as the exact same block of code is repeated twice. Since you noticed it, feel free to submit a PR to the `develop` branch removing the duplicated definitions so you can receive the contribution credit!

**Comment by disa6302** [comment]
Opened a PR because of no response on this issue. Thanks @KittyLiou for reporting it!

PR [1648](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1680)
