### ISSUE TITLE
How to control bitrate in AWS Kinesis?

### ISSUE THREAD

**Issue by Tonyinfo-dev** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#2048]
Hi all, I am trying to use kvsWebrtcclientmaster and stream.

We had applied patch to the source code so that, instead of reading from Files we are taking encoded buffers from our Embedded development SDK, and this buffer is actually encoded using H.264 encoder, now we could able to stream this in Kinesis, but problem is, we could able to see streaming in distortion at 5 Mbps, but simultaneously it streams fine in RTSP, so we don't doubt on the encoder we use.

But when we change the bitrate to 500KBytes instead of 5MBytes, we could able to see streaming without any issues.

So I doubt that AWS has issue in processing bitrate and GOP, can we know how to solve this issue by controlling bitrate in AWS side

Regards, Tony

**Comment by stefankiesz** [comment]
Hi Tony, this could be due to the bitrate of media coming from the encoder being too high for your connection. Can you do the following to see whether you're exceeding the recommended bitrate:
1. Uncomment [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/8248241cec28b651839d91f77a706f4fd028dbeb/CMakeLists.txt#L302) line from CMakeLists.txt to enable very verbose logging.
2. Run `cmake` and `make` again.
3. Set verbose log level: `export AWS_KVS_LOG_LEVEL=1`
4. Run either the master or master-GStreamer sample
5. Look for log lines with `sampleSenderBandwidthEstimationHandler(): received sender bitrate estimation: suggested bitrate`

The outputted numbers will be the adjusted suggested bitrate for your network in KBps, based on a starting point of 1024 KBps.

**Comment by stefankiesz** [comment]
Also, please share the SDK version you are using and a video clip of the distorted media if possible.

**Comment by niyatim23** [comment]
Closing due to staleness
