### ISSUE TITLE
Add selectedcandidatepairchange callback and getSelectedCandidatePair api

### ISSUE THREAD

**Issue by chehefen** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#282]

**Comment by juno52wendy** [comment]
1. I have modified the code of kvs webrtc. The callback process code is completely encapsulated according to the process style of kvs webrtc. The state value of the hole can be printed out. Register it in the Common.c file function onSelectedCandidatePairType in KVS. Master implements the callback function, and you can get the status value outside the KVS Master
2. The sample callback can get the status. The reason is to use the callback output at the outermost because sessionCleanupWait is a loop.
3, the code modified by webrtc includes the callback status of hole punching and memory modification. Using tool search for modify by juno is the modified code.
4. The modified code is in the attached compressed package: webrtc_code modification_2020.3.26.zip
5. This code has been given to aws technical support staff, and we look forward to the early 
[webrtc_code modification_2020.3.26.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4385794/webrtc_code.modification_2020.3.26.zip)

**Comment by disa6302** [comment]
Information about selected candidates and the pair can be obtained through rtcPeerConnectionGetMetrics() by setting the appropriate `RTC_STATS_TYPE`. 
Candidate pair has an active PR (#715) whereas information about selected candidates is available as part of metrics currently. Closing this ticket.
