### ISSUE TITLE
Instructions on Saving Log to Disk

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#289]
It is difficult to figure out the cause of an issue without actively monitoring real time log. It would be nice to have something in README on how to enable logging to disk.

**Comment by MushMal** [comment]
We don't have a ready-way of applying a file logger in WebRTC similar to C Producer SDK. We should add that capability.

**Comment by ycyang1229** [comment]
@suggestedfixes  I wrote one simple sample code for redirecting stdout to file. If you have interest in it, you can take a look at this commit. It is not official one because I just did it for fun.
https://github.com/ycyang1229/amazon-kinesis-video-streams-webrtc-sdk-c/commit/08ad8976534de504d37a33d3206cebbf0d587e3c
If you are interested in c producer sdk, I guess "addFileLoggerPlatformCallbacksProvider()" may be the way.

**Comment by suggestedfixes** [comment]
@ycyang1229 good idea !!!

**Comment by ycyang1229** [comment]
@suggestedfixes Glad it is helpful, but let's wait for their official design.

**Comment by disa6302** [comment]
@suggestedfixes , 

The samples in top of master now has file logging support. Closing this.
