### ISSUE TITLE
Relax Clock Requirements

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#327]
It seems like WebRTC only works if device clocks are synced with NTP. Sometimes, devices are located in an isolated internal network and don't usually have the luxury of easily accessing NTP services. I wonder if it is possible to relax the clock accuracy requirements.

**Comment by MushMal** [comment]
@suggestedfixes could you please provide more details as to what exactly is observed?

We should be somewhat close to wall clock time in order for the backend auth and communication to work.

TL;DR

Current codebase has a single GETTIME implementation which is used for measuring durations and the absolute time. Ideally, we should have two calls for measuring the wall clock for things like authentication and for durations which are used in low-level routines like timeouts or conditional variables, etc.. C producer has means of supplying the time functionality but not the WebRTC embedded SDK. We are trying to gather more information around this.

**Comment by MushMal** [comment]
Any update?

**Comment by suggestedfixes** [comment]
This is universally observed in Javascript SDK and C SDK. I think part of the clock check is handled by the Signaling service side. We have seen Javascript exceptions where the description is roughly: "the local clock needs to be less than 5 minutes of difference than actual time". But in practice, the actual timing is much more strict, roughly within 1 minute.

**Comment by MushMal** [comment]
@suggestedfixes so from your description, I am guessing that the main issue is around the absolute time and its usage in the API calls. This is, unfortunately, unavoidable due to security. Also, we are talking about minutes of drift instead of micro or milliseconds (which might impact duration calculations for thread sync or conditionals/wait).

Many of our customers call some sort of NTP library to sync up the time when their device starts. Most devices are OK to keep the clock current throughout their wake period.

I am going to resolve this. Please feel free to re-open if you need more info.
