### ISSUE TITLE
High memory usage while viewing stream

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#486]
The memory usage continues to increase while viewing stream. The free memory is 13536kB when the demo is started. When I start to view the stream, memory continues to decrease to 7212kB. At this time, I open another window to view the stream, it decreases to 1364kB. After stopping viewing, the free memory does not seem to recover as much as before, it's about 6336kB.

[high memory usage.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4671363/high.memory.usage.txt)

Since I run the kvs webrtc on my IP camera, it may lead to out of memory and my device will crush.
[iot-ipc.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/4671384/iot-ipc.log)

**Comment by MushMal** [comment]
@Nomidia the memory allocation for the WebRTC structures is minimal. The primary memory usage is allocated for the rtp buffering. There is, of course, some allocations for the websockets, ssl, dtls but the majority of memory is used in rtp buffers. As the master sample streams, it has to store the rtp buffers in order to re-transmit on request. The buffer temporal duration can be configured internally which will result in smaller heap memory usage. However, the streaming will heavily depend on the bitrate and frame rate you are streaming multiplied by the number of viewers that are connected (sessions).

The allocated memory will be properly cleaned after the application tears down.

We have something called instrumented memory allocators. You can it's usage with every simple unit test we have. We set the instrumented allocators here:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/tst/WebRTCClientTestFixture.cpp#L39

and re-set it here which also checks for total allocation size: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/tst/WebRTCClientTestFixture.cpp#L92

You can add these macro calls to your application set right after it starts in main and reset right before it exits. NOTE: you will need to compile it with `add_definitions(-DINSTRUMENTED_ALLOCATORS)`

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/tst/CMakeLists.txt#L24

**Comment by MushMal** [comment]
Forgot to mention, you can customize the following params to see how much memory vs packet loss you can tolerate

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Rtp.h#L10-L15

**Comment by Nomidia** [comment]
Thank you, I have modified the capacity of the rolling buffer.
