### ISSUE TITLE
Can we store the streamed videos?

### ISSUE THREAD

**Issue by ashutoshIITK** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#50]
Hi,

Are the videos stored anywhere (as in normal KVS)? Can we access the previously streamed video using something like GetMedia or HLS Session?

I am able to stream using Raspberry Pi and Mac and able to view only when the session is active.

**Comment by Sean-Der** [comment]
Hi @ashutoshIITK, thanks for checking out the repo!

Currently this SDK just establishes P2P sessions, the video is not saved anywhere so HLS isn't possible. We do plan in the future to support some sort of 'dual interface' so you can have both easily.

Feel free to reach out to kinesis-video-support@amazon.com we would love to help you design your systems/answer any questions! I am going to close this ticket for now since it isn't a bug/issue directly related to this project.

If you find any issues/have anything relating directly to WebRTC please re-open! thanks
