### ISSUE TITLE
[QUESTION] How to reduce CPU usage?

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#596]
I have ported Kinesis to a camera we are developing, but I found that it is using a lot of CPU. Is there some way to make Kinesis use less CPU power?
We are just reading H264 packets from our image pipeline and sending them trough Kinesis.
Our implementation is basically the same as kvsWebRTCClientMaster.c, with small changes in order to read H264 packets from a shared memory source, instead of the file sequence.

Many thanks for your attention,

**Comment by MushMal** [comment]
@fernandoc1 the sdk is designed to be as small footprint as possible and as lean as possible. Could you please provide a little more information about your platform? Are there any tools you could use to capture the cpu usage? What exactly do you mean by cpu power? Do you mean power consumption or the cpu load? Are you running your encoder in process? Is it a software encoder? Does the master sample consume the same amount of cpu?

**Comment by fernandoc1** [comment]
I have analysed the software with callgrind and it using lots of CPU in this function:
[PVOID connectionListenerReceiveDataRoutine](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/ConnectionListener.c#L217)

I have tested in my notebook with Intel i7 8th gen and Kinesis streaming is using 12% of a single CPU.

Here is my callgrind output, so you can analyse what is happening:
[callgrind.out](https://polsecai-my.sharepoint.com/:u:/g/personal/fernando_carvalho_polsec_ai/ESHd-VPTb8xCsnCdXGi2Ye8B8J1oeLbdHVlt-xHbDsunag?e=9NaqAY)

**Comment by MushMal** [comment]
This is the main receive function that sits on top of the socket. Due to platform compatibility, we can't use low-level OS features such as k-polls or on Windows waitformultipleobjectxex API. This said, it should be as fast as your sockets are doing read operation in a non-fully blocking mode (partial reads). The question is what exactly happens with the data once it's read. This is a very low-level API. Likely, the data will be passed through the DTLS (to get decrypted from the transport layer) and then passed to the consumer - in this case the application API if those are the frame bits (so it's application specific). All of this is done on the same thread and can account for the came call stack.

I don't have the tools for the callgrind. I wonder what's the best way to look into this?

**Comment by MushMal** [comment]
BTW, I assume you are running this on the stock/unmodified master sample right?

**Comment by fernandoc1** [comment]
I'm using the master branch, with just a single change to read my video chunks from the camera. My code for reading these chunks is very lightweight and is not the root for the problem, because I have tested it alone from the rest of the code.
In order to analyse callgrind output, one of my favorite tools is kcachegrind, that is available on Ubuntu's repository.

**Comment by suggestedfixes** [comment]
We have found increased CPU usage compared to last month as well.
I think it is plausible due to increased spinlocks.

**Comment by fernandoc1** [comment]
Maybe, if they start testing with Callgrind, they could figure out what is causing this issue.

**Comment by MushMal** [comment]
It's a valid point and we should take an action of adding a perf run to Travis CI jobs. I am not entirely familiar with callgrind to comment. We do have trace profiler built into the PIC which we could use to dump out the perf call stacks but haven't gotten to it yet.
