### ISSUE TITLE
[question] how do i test without having the key?

### ISSUE THREAD

**Issue by zhuker** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#622]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/01f5160431380d8fd52777a45dba41e318b433b7/tst/PeerConnectionFunctionalityTest.cpp#L156-L158

@MushMal 
there's no test which calls writeFrame and isn't disabled with this key
i think we should have a mock signaling client where something other than signaling client is tested

**Comment by MushMal** [comment]
@zhuker it's a valid point. Perhaps we should think of simulating the entire signaling but I am not sure whether it warrants the effort as when Travis CI runs with our account, it does set the credentials and executes all of the test:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/tst/WebRTCClientTestFixture.cpp#L53

So, for the local runs, we set the env variables for access key and secret key for our test account and we are able to run the tests locally.

You could try that too.

**Comment by zhuker** [comment]
> simulating the entire signaling

just thought about it

> You could try that too.

where do i get the test creds?

**Comment by zhuker** [comment]
before mock signaling is there, i think instead of silently passing tests in absence of the creds we should fail if user doesnt have them
i had false sense of security when i saw tests pass only to realize later i didnt have the creds

**Comment by lherman-cs** [comment]
@zhuker I actually had a PR opened to do this in the past, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/495. Maybe, we can just revive that?

**Comment by zhuker** [comment]
@lherman-cs i am trying to run tests locally to verify my code works before committing 

this piece of code makes tests pass locally without warning they were actually skipped 
```
 if (!mAccessKeyIdSet) { 
     return; 
 } 
```

how does #495 helps me with that?

**Comment by lherman-cs** [comment]
> before mock signaling is there, i think instead of silently passing tests in absence of the creds we should fail if user doesnt have them
> i had false sense of security when i saw tests pass only to realize later i didnt have the creds

It doesn't help with the actual problem, we won't have credentials for signaling for running unit tests. This PR will only fail early for fork builds since these builds WILL NOT have credentials anyways.

**Comment by MushMal** [comment]
RE: Credentials for the unit test. Some of the tests actually do need the credentials - for instance, the signaling client functionality test does need it as well as the tests hitting TURN. There are ways to mock those but the mocking will be pointless as we go through so many layers. Instead, we chose to use actual backend. What this evaluates to is that our Travis CI runs which are kicked under our accounts will setup the credentials and the tests will run properly. Some 3rd party PRs like this one will NOT be able to access those run-time credentials due to security concerns, etc.. Those will be manually validated by a member of the team with the credentials. 
@zhuker you can use any credentials that have appropriate rights to KVS signaling. For example, you could use your own in the local tests but for Travis CI, our engineers will check whether the changes are sensitive and touch some of the functionality that needs full backend integration in the tests and if so they will run those manually. Moreover, even in case of a failure, we will still catch those very soon when we actually push PRs from our account and execute the full integ testing.

**Comment by zhuker** [comment]
@MushMal re testing turn and signaling itself - makes sense
but why `PeerConnectionFunctionalityTest.exchangeMedia` is disabled with the `mAccessKeyIdSet`? it works with no signaling for me

**Comment by MushMal** [comment]
Hmm, it's odd. PeerConnectionFunctionalityTest.exchangeMedia doesn't need that guard as it doesn't use AWS backend functionality at all. Do you mind removing the if (!mAccessKeyIdSet) check from

* PeerConnectionFunctionalityTest.exchangeMedia
* PeerConnectionFunctionalityTest.exchangeMediaRSA

**Comment by disa6302** [comment]
@zhuker , 

Closing this since your PR is merged. Feel free to reach out for any assistance in the future!
