### ISSUE TITLE
How to create signalling channel from multiple RTSP? 

### ISSUE THREAD

**Issue by thasin96** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#635]
I am using `amazon-kinesis-video-streams-webrtc-sdk-c` to create webrtc signalling from an RTSP stream. It's working as I expected by modifying pipeline in `kvsWebRTCClientMasterGstreamerSample.c`. My question is, Is it possible to perform this same action for multiple RTSP streams and each stream for different singalling channel? In C++ producer library SDK, I can start streaming for multiple streams. I would like to perform the same scenario for webrtc too. IS it possible> If possible, What are the changes I have to make?

**Comment by MushMal** [comment]
@thasin96 these are conceptually different. For signaling, you will need to use one signaling client per channel.

**Comment by thasin96** [comment]
@MushMal - for my application I would like create signalling channel for each rtsp stream. Is it possible?

**Comment by MushMal** [comment]
For webrtc you will have to create multiple channels and each channel need to be handled by its own signaling client.

**Comment by MushMal** [comment]
The samples create a single channel and use it. Normally, this is the pattern we recommend using in order to not create/delete channels for each session. I guess, I am not sure what you are trying to accomplish conceptually but without going into details of your application, you can create a signaling channel as many times as you want (given you don't go over the limit) and reference to a particular channel by it's handle that's returned when creating the channel.

**Comment by lherman-cs** [comment]
Alternatively, you can also add multiple transceivers to a single peer connection, where each transceiver listens to an RTSP stream source. This an example how you can do this, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/ee7c30171a47d97af3ef2c8d24cef788ead24137.
