### ISSUE TITLE
[QUESTION] How to troubleshoot lag with multiple viewers open?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#637]
We had an experiment with 4 chrome tabs open connecting to a single device and VLC opening with an RTSP stream. As time goes on, the WebRTC clock and footage seems to slowly lag behind. After 10 minutes of streaming, the WebRTC stream seems to be behind 2 minutes. A colleague reported the lag can be as much as 7 minutes behind real-time.

- We are using GStreamer with an RTSP source.
- We didn't have any buffer configured, not that we are aware of.

**Comment by suggestedfixes** [comment]
One possible source of buffer is:
#define DEFAULT_JITTER_BUFFER_MAX_LATENCY (2000L * HUNDREDS_OF_NANOS_IN_A_MILLISECOND)
I think I had set that to 10000L, but that should in theory have only 10 seconds of difference correct?

**Comment by lherman-cs** [comment]
> One possible source of buffer is:
> #define DEFAULT_JITTER_BUFFER_MAX_LATENCY (2000L * HUNDREDS_OF_NANOS_IN_A_MILLISECOND)
> I think I had set that to 10000L, but that should in theory have only 10 seconds of difference correct?

Yes, we'll drop late packets, outside of 10 seconds latency, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/JitterBuffer.c#L97-L110.

Could you share the inbound-rtp stats from chrome://webrtc-internals for the 4 viewers? Also, we have an open PR that will add RTP stats, so that might be helpful to troubleshoot this problem, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/615.

**Comment by suggestedfixes** [comment]
I think I found the culprit
gstream rtspsrc has a policy drop-on-latency, so it might have queued up a bunch of rtsp frames, I'm testing with that enabled.
 
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-rtspsrc.html#GstRTSPSrc--drop-on-latency

**Comment by suggestedfixes** [comment]
I think it's in good shape now. Thanks!
