### ISSUE TITLE
[QUESTION] Customized timestamps?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#687]
We are trying to figure out how to send customized timestamps using presentationTS.
What we figured is we can use inbount-rtp from stats API from browser side.
However, my colleague reports that the timestamp displayed by the browser is the current time, not the transported time.
- An idea would be sending timestamps using data channel instead.
- Any other ideas?

timestamp | 8/4/2020, 7:48:08 PM
-- | --
ssrc | 724013749
isRemote | false
mediaType | video
kind | video
trackId | RTCMediaStreamTrack_receiver_271
transportId | RTCTransport_0_1
codecId | RTCCodec_0_Inbound_123

**Comment by lherman-cs** [comment]
Since we use the frame's presentationTS for the RTP header's timestamp (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/b11153b14d0cace10b27f0e13ea409347f6e71f8/src/source/PeerConnection/Rtp.c#L217), you can extract the presentationTS from the RTP header on the JS side (https://tools.ietf.org/html/rfc3550#section-5.1). According to w3c webrtc spec, you can get the rtpTimestamp from RTCRtpSynchronizationSource, https://w3c.github.io/webrtc-pc/#dictionary-rtcrtpsynchronizationsource-members.

So, in the JS side, you just need to get the RTP receivers, get the synchronization source, and get the timestamp by polling it.

![Screen Shot 2020-08-03 at 3 03 32 PM](https://user-images.githubusercontent.com/15654932/89434600-ba67c480-d711-11ea-9817-c5736a53dd5d.png)


Unfortunately, this seems to be only available on Chrome (I tested it on Firefox and it didn’t return any synchronization source).

Another note, since we multiply the presentationTS with the VIDEO_CLOCKRATE (90000), https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/b11153b14d0cace10b27f0e13ea409347f6e71f8/src/source/PeerConnection/Rtp.h#L78, you need to divide the timestamp that you get from the RTP header with 90000 to get presentationTS. 

Also, RTP's timestamp uses 32 bits, so you might need to handle the case when the number overflows.

**Comment by suggestedfixes** [comment]
Thanks! That was a lot of help!

**Comment by utsavrai** [comment]
Hi, I am using your suggested method to compute the latency but it seems to be increasing by a fixed value of `pSampleStreamingSession->videoTimestamp += SAMPLE_VIDEO_FRAME_DURATION;` when the rtp timestamp is received on web client. Is there any other method to compute latency per frame accurately?
