### ISSUE TITLE
[QUESTION] WebRTC metrics

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#689]
Hi, I would like to collect some metrics from the SDK, specifically:
1. if an session is using TURN or not
2. if error happens in an session, what's the error code

For the first item, seems I could use `RtcIceCandidatePairStats`, which is not implemented yet.
I would like to hear expert opinions, how do I collect those metrics.

Thanks,

**Comment by disa6302** [comment]
@staowyze , 

1. You can get information about which candidate is selected through ICE candidate stats too. That will contain information about the source of the candidate (server url for local candidate) which could be useful in your case.
2. About error codes - we log error code information currently and also do return error codes as part of any public api calls that reflects what failed. Is there anything specific you are looking for?

**Comment by staowyze** [comment]
thanks for your answers, I am looking at the sample master application, from my understanding, after initialization, the master application is triggered by audio/video writeFrame function and internal signaling channel thread, my question would be what's the best way to get error code of the signaling channel thread, probably if writeFrame fails, I can get the error from its return value.

**Comment by MushMal** [comment]
@staowyze I am not sure I understand the question. With WebRTC solution, the embedded SDK has two object graphs - one is the standardized WebRTC objects rooted to the PeerConnection and the other is the Signaling which is KVS concept. Both of the object roots (DAGs) are handled in the sample.

Signaling can return operation errors during the API call if something fails or dynamically at runtime (the callback). The error callback is called when for example updating ICE server configuration fails after the retries have been exhausted or when the re-connect fails (if configured to reconnect) after retries.

writeFrame is performed on the transceiver. If there are immediate errors, those would be returned as a result of the API call. We also have callbacks that can be monitored in the PeerConnection object graph for various conditions related to WebRTC.

Could you specify what exactly you are trying to do?

**Comment by staowyze** [comment]
Thank you, this is very valuable to me.
If I understand the SDK correctly, I could get peer connection errors via the callback `peerConnectionOnConnectionStateChange`
and signaling errors via
```
typedef struct {
    UINT32 version;                                       //!< Current version of the structure
    UINT64 customData;                                    //!< Custom data passed by the caller
    SignalingClientMessageReceivedFunc messageReceivedFn; //!< Callback registeration for received SDP
    SignalingClientErrorReportFunc errorReportFn;         //!<  Error reporting function. This is an optional member
    SignalingClientStateChangedFunc stateChangeFn;        //!< Signaling client state change callback
} SignalingClientCallbacks, *PSignalingClientCallbacks;
```

**Comment by MushMal** [comment]
No, these are purely for the signaling.

SignalingClientMessageReceivedFunc - this will be called whenever a peer sends a signaling message. You can see the usage of this in the sample. This is how the master sample receives an offer for example.
SignalingClientErrorReportFunc - this function will be called whenever the core of the SDK hits an error "dynamically". Not sure what a better term is but the signaling client has "liveness" - by default, it's configured to ensure you have a continuous connection. So, when this connection gets terminated due to a networking error or the backend signaling drops it for some reason, the SDK will automatically attempt to reconnect. Similarly, the SDK will be periodically refresh the ICE configuration automatically to ensure the peer can establish connection in lowest latency (without a need to fetch ICE server configuration before establishing). If, these ongoing background tasks fail after a number of retries, the SDK will call the application on this callback. The application can then react - for example, the sample application recreates the signaling client.
SignalingClientStateChangedFunc - this callback is called whenever the signaling client changes states. Some applications can monitor this and do certain operations when for example the signaling client goes from connected to disconnected state, etc...


Now, for the peer connection, the callback API can be set using peerConnectionOnConnectionStateChange 
 API defined in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1403. The callback will then be called whenever the peer connection changes its state. There are number of others as well - please take a look at the public include file I just referenced, for example, dealing with ICE agent state, transceiver dropped frames, etc..
