### ISSUE TITLE
[FEATURE] Create an easy way to change video/audio frame sources

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#702]
I'm working a product that is based on Kinesis for streaming through WebRTC.
I have an working version of the code that is streaming almost flawlessly, but I have some issues that I think that with time, the Kinesis staff will fix.
Due to the rapid pace that Kinesis is being updated, I would like to request an easy way to change the frame source in the master example.
My suggestion is to create an external source file that just implement a function that returns the frame buffer with its size and this is going to be consumed by the rest of the master example.
My goal is to just be able to just pull all the sources available an make small customization and get my example running with my frame source.
Every time you update the master example I have to manually introduce our customization and this is not productive.

**Comment by MushMal** [comment]
@fernandoc1 thanks for reaching out. I would like to learn about your thoughts a little more. The samples attempt to abstract the media pipeline and it's "liveness" by spinning up a thread that acts as the pipeline that produces frames for a particular type at a given cadence. For video, we have chosen pre-canned frames so we can eliminate any dependency on the actual media pipeline/encoders. We have another sample called GStreamer master sample that actually integrates with the GStreamer.

What would be the best choice for the integration for your case? One of the issue is that the media pipeline emulation has to also come with its source of "liveness" - aka the frames need to be pushed by the media pipeline and not pulled by the KVS WebRTC SDK transceiver. This is the reason we are spinning up the media source thread.

I would also like to ask a few questions about your customization - in general terms. The master sample is that - just master. It doesn't really handle many edge cases and has certain assumptions on what the master application will do - for example, starting up and continuously keeping the signaling connection open, or, the failure handling or the fact that the master sample answers to all authenticated viewer requests... Any further information might be useful. We are trying to hit a balance between the ease and readability and the functionality in the samples in this repo. We also have a demo repo which will house many samples, simple and complex, based on multiple assets.

**Comment by fernandoc1** [comment]
Here is the code from master example, that I have customized:
[main.cpp](https://gist.github.com/fernandoc1/1c31743a696833026147ef9371fa9070)
I would like to just make this simple to change the frame source, when I update the code.

**Comment by MushMal** [comment]
@fernandoc1 do you really need to pre-generate the ephemeral cert for DTLS? I would strongly recommend not doing so and letting the session to generate the cert if your hardware allows for fast generation. Some low-powered devices take multiple seconds to run the necessary crypto operation to generate the session certs and that's the reason why you can pass it along. 

With the pre-generated certificates you will need to ensure those are pre-generated for multiple sessions and have a mechanism of updating the pre-generated certificates on the background to allow no sharing of the certs between the sessions.

The certs are supplied in RtcConfiguration structure: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1012 

Regarding the media source.. I understand that your use case is a shared memory but I am not sure how we can abstract it away so it's generic for other use cases. Will think of it a little more.

**Comment by fernandoc1** [comment]
One suggestion to make it easy to replace the source is to change the "readFrameFromDisk" to a function like "readFrameFromSource", that just reads the next frame from a source. If this function is implemented in a separated source file, you could deliver an example that reads from the disk, and customers that are implementing solutions with Kinesis, just replace this file with their own implementations of "readFrameFromSource". If every Kinesis version is delivered with this would keep the updating/patching process simple.

**Comment by MushMal** [comment]
If I am reading it correctly, you are still OK to do compile-time solution rather than some dynamic solution for the media source? If so, it's pretty straight-forward. Moreover, please let me know if you want to take a stab at it and if not, we can outsource the media source into a file shortly in a priority order.

**Comment by fernandoc1** [comment]
Yes, compile time solutions would be the best for us. All I need is a reliable Kinesis streaming from our shared memory source. If you could help us dealing with this, we will be happy Kinesis customers.
Our immediate needs are:
 - Fast startup time;
 - Fast streaming start response;
 - Auto recovery from network errors;

When I start my streaming with a pre-loaded certificate, the streaming start response is very improved.

**Comment by garishsood** [comment]
Hi @fernandoc1 
 
My name is Girish and I am the product manager for Kinesis Video Streams. 

Thanks for trying the service and engaging with us on Github on different issues and enancements. 

Would you be able to email me (garisood@amazon.com) the details of your usecase and the your timeline expectations for this feature. This information shall help us prioritize the feature request appropriately or suggest alternatives.

Best,
-G

**Comment by chehefen** [comment]
@fernandoc1 can't you make a copy of Common.c and make it part of the object files of your application? Then every time you update the sdk you just need to link against libkvsWebrtcClient.so and libkvsWebrtcSignalingClient.so and not be concerned about what changed in the sample.

**Comment by fernandoc1** [comment]
This is a option, but I ask:
- What happens when you update and improve Common.c/kvsWebRTCClientMaster.c file, how will I patch all the changes?
- What happens when you change the interfaces exposed in libkvsWebrtcClient.so and libkvsWebrtcSignalingClient.so?
My goal is to just make easy for customers that just need the kvsWebRTCClientMaster.c example working, but with a different frame source.
The other requirement I need it is an easy way to use predefined certificates in order to improve the video startup process. The description that is in the README is not working for me.

**Comment by chehefen** [comment]
what patch do you need in Common.c? We've been careful to not make interface changes in libkvsWebrtcClient and libkvsWebrtcSignalingClient and if we do we would bump the major version.

**Comment by disa6302** [comment]
@fernandoc1 , 

Any updates?

**Comment by disa6302** [comment]
@fernandoc1 , 

Closing this issue since it has gone stale. Feel free to reach out if you have any questions
