### ISSUE TITLE
[FEATURE] Add error callback to PeerConnection

### ISSUE THREAD

**Issue by lherman-cs** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#703]
**Is your feature request related to a problem? Please describe.**
Getting error codes from PeerConnection is not possible when the error itself happened in the background. 

For example, when the ICE agent fails at the connectivity checks and no ICE candidate pairs were formed, we can't get the error code that caused this. We can only get the state updated to `FAILED` through registering a callback with `peerConnectionOnConnectionStateChange`.

**Describe the solution you'd like**
I think we should let the user to provide an optional error callback, similar to what we have for Signaling:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/1d8a292a538f0db046de77589a285895bd2a7331/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1222-L1231

Then, the user can capture the error code by registering a callback:

Registration:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/1d8a292a538f0db046de77589a285895bd2a7331/samples/Common.c#L721

Handler:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/1d8a292a538f0db046de77589a285895bd2a7331/samples/Common.c#L106-L119

**Comment by fernandoc1** [comment]
It would be nice if there were a feature to handle all errors in a user defined function callback.
In my case for example, I have a log service, based on ubus and if I could send any error messages to this service, it would make debugging easier.

**Comment by MushMal** [comment]
There are few aspects that I would like to clarify/add some food for thought. This is a great discussion, please keep this going

1) The case with signaling callback. This works great for the errors that happen at runtime or what's called "dynamic" errors. However, we still have the same issue on the public APIs. Unlike KVS Producer APIs which have SYNC APIs sitting on top of public ASYNC API where the customers can directly use ASYNC version, the Signaling API only provides SYNC API. So, CreateSignalingChannel or Connect API is only SYNC and will iterate on failures multiple times and eventually fail with a timeout, not exposing the errors on the way. I don't have a very good and clean way of handling this situation - calling a callback while a sync API is still in progress might be good and bad - good for recording the error and bad as applications will have to be very careful with the steps they will need to take on failure and be mindful of the threading model.
2) KVS WebRTC solution is based on two top level objects (with their corresponding DAGs). One is the Signaling client and the other is the PeerConnection object. We specifically kept them separate due to the W3C standards. However, this said, the customers application can supply the exact same handler to the different error callbacks and process errors in a single function - not sure whether it's a good idea though.

**Comment by disa6302** [comment]
This feature item is being tracked by the team internally.
