### ISSUE TITLE
[FEATURE] Documentation improvement

### ISSUE THREAD

**Issue by disa6302** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#737]
**Is your feature request related to a problem? Please describe.**
We need to improve upon our debug guide to allow customers to try certain things to help alleviate their problems. The following is a list of items that need to be added:

- [ ] Debug Signaling related issues
- [ ] Debug connectivity issues
- [ ] Debug build issues
- [ ] Gstreamer debug tips
- [ ] Debug streaming issues - for example, lost frames, choppy video, etc
- [ ] Simple connectivity checks apart from `discoverNatBehavior` utility
- [ ] Include a simple way to know what function that allocates memory the most. Adding this section can help some users to discover memory leaks or, at least, some pointers to memory leaks. (#408 )
- [ ] Document on how P2P is set up in the SDK
- [ ] Document status codes

**Comment by fernandoc1** [comment]
This would be great.
I think that should be a module that we could attach to Kinesis in order to read it's internal registers. For example, a internal console that could be remotely connected or a simple Web server that could be activated for debugging purposes. I'm in a huge trouble trying to understand why my signaling process sometimes fails, and sometime it succeed. I'm also having issues with P2P connections that fail and succeed without a clear pattern of events that could be reproduced.
If we could also have a logging facility, I would help a lot.

**Comment by suggestedfixes** [comment]
Gstreamer debug tips were pretty helpful as well.

**Comment by fernandoc1** [comment]
Hi @disa6302, would you mind adding to your documentation improvement, some simple connectivity tests that can be run apart from Kinesis in order to check exactly what operation failed?
For example, there could be an application that just use STUN to create candidates and another application that tries to connect to it. By doing so, we should see where is the failure.
Libnice has an example about what I'm saying. [libnice-simple-example](https://gitlab.freedesktop.org/libnice/libnice/-/blob/master/examples/simple-example.c)
I think that some real world test applications would improve a lot our understanding of the problems.

**Comment by disa6302** [comment]
@fernandoc1 , 

Sounds like a good suggestion! Will surely look into it.

**Comment by disa6302** [comment]
This item is being tracked by the team internally.
