### ISSUE TITLE
[QUESTION] Switching stream sources using the same transceiver

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#742]
- We have been experimenting with switching between live stream sources with the same video transceiver on the fly. This has worked pretty well if we change the resolution and bitrate, the changes are instantaneous.
- If we were to switch between live source and file source on the fly. We are seeing a weird phenomenon:
  - The browser is receiving new video data from file source (made of h264 keyframes and delta frames), but it is not able to decode the video 20-30 seconds later. But eventually, it does decode. We used chrome://webrtc-internals to figure out this is happening.

Our suspicions:
- codec from file source is a bit different from live source.
- timestamps need to be monotonically increasing.
- frame index needs to be monotonically increasing, we reseted them after switching to file source. 
- we are missing SPS and PPS frames from our file source.

Possible workarounds/improvements to mitigate:
- have two video transceivers, one for live, another one of file source. Would this work a bit better?

Any other insights?

**Comment by MushMal** [comment]
The issue you are seeing is due to different codec private datas. In case of H264, it's SPS and PPS. The elementary stream that you are using comes in a form of Annex-B format NALs where the IDR frame has the SPS and PPS NALs prepended.

The decoder implementation can at times skip frames until it gets to the new IDR and is able to extract new CPDs. Not every decoder can recover.

Regarding two transceivers. Theoretically, it should work OK. However, some hardware can be limited to a single context so on the producing and the receiving end you might need to free up hardware resources in order to context switch.

Recommend trying it, we currently don't have the complete test matrix for these scenarios across platforms/versions.

**Comment by suggestedfixes** [comment]
Thanks! We will try them out!
