### ISSUE TITLE
Master loses connection to signaling channel (no memory issues)

### ISSUE THREAD

**Issue by sbarry157** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#752]
I'm separating this issue from #729 .

#729 streaming issues are accompanied by low memory warnings. But there are times when streaming stops working and we DO NOT observe low free memory. When this happens, we also noticed that the signaling channel cloudwatch metrics show that master is not connecting to the signaling channel. Here is an example of a camera that lost the ability to stream, during which time master fails to reconnect to signaling.

![Screen Shot 2020-08-26 at 11 45 52 AM](https://user-images.githubusercontent.com/7031937/91325924-bddef080-e791-11ea-964c-527af5983735.png)

Rebooting always fixes this problem.

This problem has thus far been replicated by customers and we haven't been able to capture verbose logs. We are working to provide firmware that is capable of producing verbose logs and will add to this issue with logs as soon as possible.

**Comment by MushMal** [comment]
Unfortunately, this issue is not possible to transact upon due to the lack of requested information such as verbose logs and logs from debug version of libWebSockets. We can't replicate this locally so hope you succeed with capturing more info that we can transact. I am also replacing BUG label as I am not convinced that this is not network topology specific or device specific.

**Comment by disa6302** [comment]
Closing this for now. @sbarry157 , feel free to open a new issue when you capture some logs.
