### ISSUE TITLE
create Iot credential provider causes crash

### ISSUE THREAD

**Issue by staowyze** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#787]
**Describe the bug**
If the NIC is down, create Iot credential provider in the sample code would cause crash, see the crash errors

**SDK version number**
1.3

```
[2020/09/11 15:23:44:8122] N: lws_tls_client_create_vhost_context: doing cert filepath /tmp/aws_iot/cert.pem
[2020[ 1379.822684] do_page_fault() #2: sending SIGSEGV to kvsWebrtcClient for invalid read access from
[ 1379.822684] 0000000c (epc == 773a0f74, ra == 7756c8e0)
/09/11 15:23:44:8142] N: Loaded client cert /tmp/aws_iot/cert.pem
[2020/09/11 15:23:44:8144] N: lws_tls_client_create_vhost_context: doing private key filepath
[2020/09/11 15:23:44:8156] N: Loaded client cert private key /tmp/aws_iot/privkey.pem
[2020/09/11 15:23:44:8177] E: getaddrinfo failed: -2
[2020-08-11 15:23:44] [KVS]lwsIotCallbackRoutine(): Client connection failed. Connection error string: getaddrinfo failed
Segmentation fault
```

**Comment by MushMal** [comment]
Could you please get the crash stacks for all of the threads for debug build so we can see what’s going on?

I can also try to reproduce with the steps you are describing- namely, use IoT credentials provider with no network.

**Comment by staowyze** [comment]
I tried then I realized this is not a crash, even though the log says `SIGSEGV`. I guess the seg fault was caught somewhere.
Yeah, i can reproduce it easily, just `ifconfig eth0 down`.

**Comment by MushMal** [comment]
Must be in your application. Here is my recommendation.

1) Try to reproduce the issue with the stock master sample application
2) If you are able to reproduce the crash, please get the full stack dump so we can look

If we are unable to reproduce and don't have the full stack traces then we won't be able to act on this issue

**Comment by staowyze** [comment]
hm... seems it's not reproducible on my ubuntu machine, only my mips device has the issue.
i cannot catch the stack trace on the device, keep digging...

**Comment by staowyze** [comment]
i was trying to find some example applications from Producer C, to check if they would crash on my device.
but seems not example applications are available if BUILD_COMMON_LWS is ON, is there anything I could try with BUILD_COMMON_LWS ON?

**Comment by zhuker** [comment]
@MushMal @staowyze looks like it may be caused by unaligned address read/write on mips

**Comment by MushMal** [comment]
@staowyze C Producer is getting compiled to use libCurl instead of LWS so you won't be able to do it with ease.

@zhuker, there is no unaligned access in the SDK when it comes to signaling path. The only unaligned access is in the content store which is only specific to c producer.


Recommend trying to reproduce this in various configurations. Please run the stock sample applications without any modifications but just the IoT credential provider. Try to get the debug logs to see if they can shed some light. Try to compile libWebSockets in debug mode. Include the SDK commit version, though, I doubt it has anything to do with it. As the signal gets caught, it seems that your application catches it and does something with it. If it's not possible to run this under the debugger, at least run the debug version of the stock sample and let it crash. Configure your OS signal handler to try to capture the crash stack.

**Comment by staowyze** [comment]
ok, will take a try, thank you!

**Comment by staowyze** [comment]
i got the core dump, it turns out the sample application crashed, the logs are interleaved together, causes confusion.
close for now.
