### ISSUE TITLE
[QUESTION] Sample code porting issues on the Grand Media platform

### ISSUE THREAD

**Issue by jonescx** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#796]
We use the latest SDK and the sample code with sample video frames to make it runs on our platform.
There are two issues.

First, it works on KVS webrtc test page and customer's web app. However, it always connects fail on echo show.
In the attached console log, it shows 2 times of failure.
[09-15 11:56:45]2020-09-15 03:56:45 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a000013
[09-15 11:56:45]2020-09-15 03:56:45 DEBUG   freeSampleStreamingSession(): Freeing streaming session with peer id: echoshow614 

[09-15 11:57:40]2020-09-15 03:57:40 ERROR   executeFailedIceAgentState(): IceAgent failed with 0x5a000013
[09-15 11:57:40]2020-09-15 03:57:40 DEBUG   freeSampleStreamingSession(): Freeing streaming session with peer id: echoshow791 

Second, the application will crash when it get into the onFrameDroppedFunc function.
We disable that function and only print out a message to avoid this issue. 
Here is the ticket we created before.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/778

We will provide the sample codes, build environment and documents for setup and testing later.

[webrtc_0915_echo_show_fail.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5222402/webrtc_0915_echo_show_fail.txt)

**Comment by MushMal** [comment]
@jonescx the log doesn't really tell us much - it just states that it failed to nominate the ice pair: STATUS_ICE_FAILED_TO_NOMINATE_CANDIDATE_PAIR which is 0x5a000013

Could this issue be caused by your network or the topology somehow? Can you reproduce this on non-device with stock master? I suspect something odd must be going on with the network.

Regarding the crash... Let's not track it here as it's being tracked in #778, the suggestion is to check your code and the callback handler to ensure you capture the debug crash stacks that will give you some clues as to what might be wrong with your code

**Comment by sbarry157** [comment]
Here is an example of the streaming failing using an echo show to initiate the stream with error code 0x5a000013. But streaming is working when initiated using a browser:

2020-09-15 14:53:44 - Streaming worked using the browser
2020-09-15 14:55:28 - Streaming failed using echo show

[CMAX-513-2020-09-15 10-53-40 FT230X Basic UART #1.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5229164/CMAX-513-2020-09-15.10-53-40.FT230X.Basic.UART.1.log)

**Comment by jonescx** [comment]
@MushMal We've already provided source code with stock master and toolkit of our platform to @sbarry157. Sean will pass the whole package to your team, please make sure you have device with UART output to setup the environment. If you have any question, please feel free to let us know.

**Comment by MushMal** [comment]
@jonescx @sbarry157 Ideally, we would prefer to not debug custom software on custom hardware platforms but rather rely on repro on the samples on a generic platform such as Linux. Could I ask you folks to also try to reproduce these issues on commodity platforms so we can identify the root causes easier?

**Comment by jonescx** [comment]
@MushMal I think the network is fine. I use the same network and same device to test.
The webrtc master application that we develop works on both web app and echo show.
The sample code application only works on web app but not echo show (always fail, never success)
Do you have idea where we can add some instrumentation to figure out this problem?

**Comment by MushMal** [comment]
@jonescx without any understanding what is wrong I can't recommend any actual steps. We really need to start converging with the scenarios. For that, we will need your team to pin point the issues and ensure we are constantly looking at the same thing and that we can trust the experiments.

The sample log that @sbarry157 attached contains a successful streaming session and following it there is one that fails.

The master receives the message at `09-15 10:55:28.725: 2020-09-15 14:55:28 DEBUG   lwsWssCallbackRoutine(): Client receive `

It starts the session, kicks off the ICE agent and has the answer submitted at

`09-15 10:55:30.485:         "action": "SDP_ANSWER",`

which is 2 seconds after

After the Trickle ICE exchanges, we end up binding to a TURN pair and getting it to ready

`09-15 10:55:32.903: 2020-09-15 14:55:32 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_BIND_CHANNEL to TURN_STATE_READY
`
What happens then is odd

```
09-15 10:55:33.681: 2020-09-15 14:55:33 DEBUG   dtlsTransmissionTimerCallback(): DTLS handshake timeout event
09-15 10:55:38.013: 2020-09-15 14:55:37 DEBUG   dtlsTransmissionTimerCallback(): DTLS handshake timeout event
```

We have the first DTLS timeout and the second one in 5 seconds.

We do the cleanup later in
`09-15 10:55:42.066: 2020-09-15 14:55:41 WARN    turnConnectionStepState(): TurnConnection in TURN_STATE_FAILED due to 0x58000022. Aborting TurnConnection
`

I am not sure what exactly is going on with the turn connection. Is it possible that the media pipeline is simply stopped somehow? Is it possible that the socket goes 'bad' somehow? Networking? I am just not sure yet how to debug these issues. 

My recommendation still stands - try to stabilize your software on an "open" platform - run it simply on a PC with Linux for example. This will give you an opportunity to remove any bugs that you might have in your application code first before actually attempting to debug on a physical device which would be far more confined.

**Comment by jonescx** [comment]
@MushMal  @sbarry157 We found the root cause of echo show cannot connect. It's because the tricleIce is TRUE in the sample code. It must be FALSE for echo show connection.

`STATUS createSampleConfiguration(PCHAR channelName, SIGNALING_CHANNEL_ROLE_TYPE roleType, BOOL trickleIce, BOOL useTurn, PSampleConfiguration* ppSampleConfiguration)`

**Comment by MushMal** [comment]
Oooookay! Thanks for this, entirely forgot to mention it.
