### ISSUE TITLE
[BUG]-Webrtc master responses the SDP_OFFER of Echo Show too late, the live streaming will be failed.

### ISSUE THREAD

**Issue by coolzsf** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#818]
**Describe the bug**
Sometimes the Echo Show live streaming of camera will be failed.

**SDK version number**
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/910a67c822a2bd9e14e3271a81cb57516add2b6e
https://github.com/awslabs/amazon-kinesis-video-streams-pic/commit/f362b4083366df2e3b1f56a860bf7dd474912fbe
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/commit/e7d4868d8c336cec5fa35250212fffa19135a6ba

**To Reproduce**
1. Setup the camera as a webrtc master
2. Check the live streaming of camera by Echo Show
3. Test it about 10 - 20 times, the live streaming will be failed once.
4. See error log. Please check the line 20030 to line 20071. The master took too long time to create the peer connection.
[webrtc_log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5267313/webrtc_log.txt)
5.It seems that createPeerConnection is locked by ICE config. Please check the lines marked with green color.
![图片](https://user-images.githubusercontent.com/46127053/93999290-37392580-fdc8-11ea-989a-6a2d2569cbad.png)

Thanks!

Phil
Sercomm

**Comment by MushMal** [comment]
It's not immediately clear from the picture you've attached but it looks like after it received the message the master is refreshing the ICE candidates which causes the blockage.

Can you describe your scenario and the devices in more details? How often does this happen? How often do you invoke the master? The ICE refresh logic is kicked off in the background prior to the TURN credentials expiration. 

Looking at the full logs, I do see indeed that in LN 19984 signaling client reconnection fails and it issues an error, which then the sample application handles by re-starting the signaling client

```
[2020-08-05 12:09:37 714495] signalingClientError(128): Signaling client generated an error 0x5d000030 - 'Failed to reconnect with status code 0x0000000f.'
[2020-08-05 12:09:37 715049] freeSignalingClient(39): Freeing Signaling Client

```

While the signaling client is being brought up the message comes in which gets handled.

Another thing to note, in order to handle echo show case, you will need to disable Trickle ICE as Alexa does not support it.

Another note: Try to provide a filter for the interfaces that will not be used for the communication. For example, your device might have an ethernet which might take a while for the socket create/bind to timeout and fail and it will block the ICE agent.

**Comment by coolzsf** [comment]
Thanks for your response. 
We have disabled the Trickle ICE and filtered the useless interface already.
Our camera and Echo Show is located at Suzhou China, Alexa Lambda region is Virginia, and the KVS region is Oregon.
We tested it about 10 times and it happened once. And we waited about 3 minutes before next test.

**Comment by MushMal** [comment]
See if your network has packet loss but in general Alexa will timeout in 6 seconds all together. Having multiple cross region calls might be getting too close to the timeout

**Comment by coolzsf** [comment]
We'll do more tests to verify it.

**Comment by MushMal** [comment]
Resolving due to staleness. Please cut a new issue if you need help
