### ISSUE TITLE
[QUESTION] : How much minimum bandwitdh internet speed required by aws webrtc sdk to get smooth AV ?

### ISSUE THREAD

**Issue by shiv50084** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#869]
As i am configure my router at speed of 512Kbps with this to get AV data on viewer its take around ~5 Minutes and video is also not smooth.

While my master and viewer on same network. My video video resolution is 640x480 at 10 FPS.

master running on MIPS-arch 32bit system. and viewer running on google chrome browser. Test link is :-  "https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html"

**Comment by hassanctech** [comment]
You will need to know the estimated bitrate of your video.  Does your encoder have a max bitrate option you can set if you're running in a constrained environment?  The bitrate will depend on more than just the resolution and frame rate, also the key frame interval.

For example for standard RGB uncompressed frames you have 24 bits (3 bytes) per pixel * 640 * 480 = 920Kb. 

With any compression algorithm the key-frame isn't really compressed so if your key-frame interval is similar to your frame rate, i.e. 1 per second, then you can expect at least 1 Mbps bit rate.  If your key frame interval is much longer like 3s then perhaps you can achieve 512kbps if there isn't much motion.  But the first step for you is to determine your video bit rate.  Here are some options:

If you have more available bandwidth try increasing the router speed incrementally until the video is smooth.  

If you've set the encoder to do variable bit rate without a max then you will never really have a guarantee that you won't exceed 512kbps because depending on the type of video like if there's motion or a lot of noise (which is hard to compress), the bit rate will increase significantly.

For an idea streaming scenario you will want to cap your bit rate to something below your router speed, perhaps at 80% of the router speed, so maybe 400kbps, increasing your key frame interval will help with that, I would suggest 2-3s.  But know if you are aggressive with the max bitrate setting and the video itself is not compressible the encoder really has only 2 options:  drop frames or degrade the quality -- so expect to see those artifacts.

**Comment by MushMal** [comment]
Bandwidth and latency are somewhat orthogonal. The required bandwidth is a direct consequence of the encoder and the settings. 

Resolving. Please reopen if you have detailed questions about KVS
