### ISSUE TITLE
Audio Backchannel latency

### ISSUE THREAD

**Issue by jvasanthan** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#887]
Hi Team, 
Setup: Device as Master (sends out Audio, Video and receives audio) and js as viewer (sends out audio, received video & audio)
SDK : latest in both device & js
Issue: The latency of audio received from js viewer to device master grows gradually to more than 5-10 seconds. I didn't notice any latency on the video & audio from master to viewer though. 
@MushMal could you please direct me where to look for and how to fix the latency. pfa log file, what other debug information you need to check 

[audio_latency.txt](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5414332/audio_latency.txt)

**Comment by MushMal** [comment]
I don't see anything that could suggest delay in the logs. Can you try to run with verbose logging and see whether the network is the issue or your media pipeline is the issue. Try different network configurations so eliminate the networking. 

Try to run master and viewer in TURN and P2P modes for example to eliminate the potential networking issue.

**Comment by hassanctech** [comment]
@jvasanthan any updates here?

**Comment by jvasanthan** [comment]
@hassanctech I checked with different networks but the issue was still there. I am checking the media pipeline. will post update here soon.

**Comment by MushMal** [comment]
Closing this for now. Seems that media pipeline related. Suggest doing deep dive into the verbose level logs for you to understand whether it's your media pipeline or the startup latencies. If this is a startup latency, try to provide detailed information/logs so we can understand why. In some cases, due to not filtered interfaces, the ICE gathering state hangs and waits until the interface socket times out. For example, if you have a device with both LAN and WiFi, and you are not using LAN, it will add latency as we will be querying all ICE candidates. In this case you should provide an interface filter to remove the unused interface.
