### ISSUE TITLE
[QUESTION] Measure Video/Audio Latency

### ISSUE THREAD

**Issue by wlinInspire** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#897]
Hi,

Was wondering if there exists any function in the code to report the video or audio latency between master and client.  I don't think `cpApiCallLatency` or `dpApiCallLatency` measure that metric. Thank you so much!

Wei

**Comment by hassanctech** [comment]
We do not have anything like this.  This might be helpful though:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/687#issuecomment-669274565

**Comment by MushMal** [comment]
There can't be a simple metrics as it includes two parties in order to measure the latency.

You can check out the demo repository for the latency metrics and run publicly available "canary" code and get this per-frame latency graph in your CW.

https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/canary/webrtc-c

I am going to resolve this issue for now

**Comment by utsavrai** [comment]
Hi, I am using your suggested method to compute the latency but it seems to be increasing by a fixed value of pSampleStreamingSession->videoTimestamp += SAMPLE_VIDEO_FRAME_DURATION; when the rtp timestamp is received on web client. Is there any other method to compute latency per frame accurately?
