### ISSUE TITLE
echo show send received SDP

### ISSUE THREAD

**Issue by pai-da-xin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#953]
Hi, experts,
After testing, I found that the offer sent by Amazon echo show is different from the normal offer. The offer sent by Amazon echo show does not use base64 encoding, so base64 decoding is not used. In addition, the Amazon echo show offer has fewer fields than the normal offer.
such as, a normal offer contains the following fields: `"type":"offer","sdp":`. The offer sent by Amazon echo show does not have these, this will cause errors in [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/SessionDescription.c#L121). So need to change the code, It's a big challenge for me, so do you have any suggestions.

**Comment by lherman-cs** [comment]
@pai-da-xin unfortunately, signaling messages have to be base64 encoded as stated here, https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-websocket-apis3.html. 

To get around this, you can try to encode the message payload in base64 before deserializing it.

Since there's no action item for us, I'll mark this as resolved.
