### ISSUE TITLE
[QUESTION] Is there any crash related issue fixed between tag v1.3.0 and tag v1.4.0?

### ISSUE THREAD

**Issue by jonescx** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#963]
We got a webrtc master crash without any peer connection with SDK tag v1.3.0.
This issue is not easy to reproduce and we want to know if there important crash fix after v1.3.0.
Thanks.

** Logging ** 
See the attached log file.
[webrtc_master_crash.log](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/files/5559652/webrtc_master_crash.log)

**Comment by MushMal** [comment]
From the crash stack I can't even tell which API is a the top of the stack. It's not much help.

There were a few stability fixes that went in between 1.3.0 and 1.4.0. There were a few potential race conditions fixed in the Signaling and ICE. There were more fixes in the sample.

Can you try to narrow your question down to make it more actionable?

**Comment by jonescx** [comment]
Thanks for replying. We will upgrade to version 1.4.0.
