### ISSUE TITLE
[BUG] Audio only operation needs tweak to kvsWebRTCClientMaster.c

### ISSUE THREAD

**Issue by gregshay79** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#983]
Audio is distorted with the unmodified C client master, when running in audio only mode.

When the Viewer client is set to request audio only, the master correctly generates audio only SDP. However
the audio is distorted because of some conflict with sendVideoPackets thread.

Modification in kvsWebRTCClientMaster.c disables sendVideoPackets thread and allows audio-only mode without distortion.

    pSampleConfiguration->videoSource = 0;//sendVideoPackets;
 

--- Note:  Configuration of the example js client for audio only is as follows:
In viewer.js:
        // Create an SDP offer to send to the master
        console.log('[VIEWER] Creating SDP offer');
        await viewer.peerConnection.setLocalDescription(
            await viewer.peerConnection.createOffer({
                offerToReceiveAudio: true,
                **offerToReceiveVideo: false,**
            }),
        );

And to have the browser use an audio player:
test page html:
...
```
        <div id="viewer" class="d-none">
            <h2>Viewer</h2>
            <div class="row">
                <div class="col">
                    <h5>Return Channel</h5>
                    <div class="audio-container"><audio class="local-view" autoplay="" playsinline="" controls="" muted=""></audio></div>
                </div>
                <div class="col">
                    <h5>From Master</h5>
                    <div class="audio-container"><audio class="remote-view" autoplay="" playsinline="" controls=""></audio></div>
                </div>
            </div>
```
...

-----------------

**Comment by disa6302** [comment]
@gregshay79 ,

Thanks for adding the details. The sample is intended to do both audio and video streaming. If you would like audio streaming only, you will have to remove all video related code in the samples that includes removing addition of video transceiver (using the `addTransceiver()`) call. 

And setting `pSampleConfiguration->videoSource` to NULL/0 is the right thing to do. 

Also, if you are letting the video thread run without removing the `addTransceiver()` call for video, I think it would segfault/not work at all because `writeFrame()` in sendVideoPackets()` uses the created transceiver. 

So I am not sure how your audio was distorted.

**Comment by disa6302** [comment]
Closing since this has gone stale.
